apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: dgoodwin-dev-t6drv
  name: dgoodwin-dev-t6drv-additional-compute
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: dgoodwin-dev-t6drv
      machine.openshift.io/cluster-api-machine-role: worker
      machine.openshift.io/cluster-api-machine-type: worker
      machine.openshift.io/cluster-api-machineset: dgoodwin-dev-t6drv-worker-us-east-1c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: dgoodwin-dev-t6drv
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: dgoodwin-dev-t6drv-worker-us-east-1c
    spec:
      providerSpec:
        value:
          ami:
            id: ami-046fe691f52a953f9
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 22
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ocp-gkzoprdgmozpkzy20-sqlpj-worker-profile
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: sa-east-1c
            region: sa-east-1	
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - ocp-gkzoprdgmozpkzy20-sqlpj-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - ocp-gkzoprdgmozpkzy20-sqlpj-private-sa-east-1c
          tags:
          - name: kubernetes.io/cluster/dgoodwin-dev-t6drv
            value: owned
          userDataSecret:
            name: worker-user-data
